name: CI on Pull Requests

on:
  pull_request_target:
    branches: '**'
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint using PyLint and PyCodestyle
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      - name: Run PyLint
        run: |
          find . -name '*.py' -exec pylint {} +
      - name: Run PyCodestyle for Jupyter Notebooks
        run: |
          find . -name '*.ipynb' -exec pycodestyle --show-source --show-pep8 --config=.pycodestylerc {} +
